### ISSUE TITLE
cutefetch: cant get os name on fedora

### ISSUE THREAD

**Issue by sammy-ette** [rayes0/scripts#1]
browsing through the code for cutefetch, i see the method for getting the distro name is by using `lsb_release`
this is actually not available on fedora
a better (and simpler) method is to source `/etc/os-release` and use either $NAME or $PRETTY_NAME, which should be available on any distro

**Comment by sammy-ette** [comment]
simple screenshot to illustrate: ![](https://modeus.is-inside.me/Dph5WSzS.png)

**Comment by rayes0** [comment]
Should be fixed now :)
